---
config:
  theme: neo
  look: neo
---
flowchart LR
    A["Aplikasi Mobile SI-FASKAM<br>(Flutter)"] -->|"HTTP Request<br>(JSON)"| B["Backend SI-FASKAM<br>(REST API)"]
    B -->|"Query atau perubahan data"| C[("Database SI-FASKAM<br>(pengguna, pengaduan, status)")]
    C -->|"Data hasil query"| B
    B -->|"HTTP Response<br>(JSON)"| A